// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search_products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/helpers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";

// src/lib/mcp/audit.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function adminClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
async function hashInput(input) {
  const json = JSON.stringify(input ?? {});
  const buf = new TextEncoder().encode(json);
  const digest = await crypto.subtle.digest("SHA-256", buf);
  return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
function summariseInput(input) {
  if (!input || typeof input !== "object") return {};
  const out = {};
  for (const [k, v] of Object.entries(input)) {
    out[k] = v == null ? "null" : typeof v === "string" ? `string(len=${v.length})` : Array.isArray(v) ? `array(len=${v.length})` : typeof v;
  }
  return out;
}
async function recordMcpCall(params) {
  try {
    const supabase = adminClient();
    const input_hash = await hashInput(params.input);
    await supabase.from("mcp_audit_log").insert({
      tool_name: params.toolName,
      user_id: params.ctx.isAuthenticated() ? params.ctx.getUserId() : null,
      client_id: params.ctx.getClientId?.() ?? null,
      input_hash,
      input_summary: summariseInput(params.input),
      duration_ms: params.durationMs,
      status: params.status,
      error: params.error?.slice(0, 500) ?? null
    });
  } catch {
  }
}

// src/lib/mcp/rateLimit.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
function adminClient2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
async function checkRateLimit(toolName, ctx) {
  if (!ctx.isAuthenticated()) return { ok: true };
  try {
    const supabase = adminClient2();
    const { data, error } = await supabase.rpc("mcp_check_rate_limit", {
      _user: ctx.getUserId(),
      _tool: toolName
    });
    if (error) return { ok: true };
    const result = data;
    if (result && result.ok === false) {
      return { ok: false, reason: result.reason ?? "Rate limit exceeded." };
    }
    return { ok: true };
  } catch {
    return { ok: true };
  }
}

// src/lib/mcp/helpers.ts
function supabaseForUser(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function withAudit(toolName, fn) {
  return async (args, ctx) => {
    const started = Date.now();
    const gate = await checkRateLimit(toolName, ctx);
    if (gate.ok === false) {
      const reason = gate.reason;
      let retryHint = "Please retry shortly.";
      if (/per minute/i.test(reason)) retryHint = "Try again in about 60 seconds.";
      else if (/per hour/i.test(reason)) retryHint = "Try again in about an hour.";
      else if (/24 hours|per day/i.test(reason)) retryHint = "Your daily quota resets in 24 hours \u2014 try again tomorrow.";
      const friendly = `\u23F3 ${reason}

${retryHint}

This limit protects Houskase from runaway agent retries. If you need higher limits, contact the Houskase team.`;
      recordMcpCall({
        toolName,
        input: args,
        ctx,
        durationMs: Date.now() - started,
        status: "error",
        error: `rate_limited: ${reason}`
      });
      return {
        content: [{ type: "text", text: friendly }],
        isError: true
      };
    }
    try {
      const result = await fn(args, ctx);
      recordMcpCall({
        toolName,
        input: args,
        ctx,
        durationMs: Date.now() - started,
        status: "ok"
      });
      return result;
    } catch (err) {
      recordMcpCall({
        toolName,
        input: args,
        ctx,
        durationMs: Date.now() - started,
        status: "error",
        error: err instanceof Error ? err.message : String(err)
      });
      throw err;
    }
  };
}

// src/lib/mcp/tools/search_products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search Houskase products",
  description: "Search the Houskase catalog by keyword and/or category. Returns product name, slug, short description, price, MOQ, and stock.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text search across name and description."),
    category_slug: z.string().trim().optional().describe("Filter by category slug (optional)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("search_products", async ({ query, category_slug, limit }, ctx) => {
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("products").select("id, name, slug, short_description, guest_price, shop_price, shop_moq, stock_quantity, category:categories(name, slug)").eq("is_active", true).limit(limit ?? 20);
    if (query) {
      const safe = query.replace(/[,()]/g, " ").replace(/[\\%_]/g, (m) => `\\${m}`).trim().slice(0, 100);
      if (safe) {
        q = q.or(`name.ilike.%${safe}%,short_description.ilike.%${safe}%`);
      }
    }
    if (category_slug) q = q.eq("categories.slug", category_slug);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  })
});

// src/lib/mcp/tools/get_product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch full details for a single Houskase product by id or slug \u2014 description, features, images, pricing, and stock.",
  inputSchema: {
    id: z2.string().trim().optional().describe("Product UUID."),
    slug: z2.string().trim().optional().describe("Product slug (alternative to id).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("get_product", async ({ id, slug }, ctx) => {
    if (!id && !slug) return { content: [{ type: "text", text: "Provide either id or slug." }], isError: true };
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("products").select("*, category:categories(name, slug), brand:brands(name)").limit(1);
    q = id ? q.eq("id", id) : q.eq("slug", slug);
    const { data, error } = await q.maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Product not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { product: data }
    };
  })
});

// src/lib/mcp/tools/list_categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List product categories",
  description: "List all active product categories on Houskase (name, slug, parent).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("list_categories", async (_input, ctx) => {
    const { data, error } = await supabaseForUser(ctx).from("categories").select("id, name, slug, parent_id").order("name");
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { categories: data ?? [] }
    };
  })
});

// src/lib/mcp/tools/list_my_orders.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool4({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in user's Houskase orders \u2014 id, order number, status, payment status, total, placed date. RLS restricts to the caller's own orders.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("list_my_orders", async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("orders").select("id, order_number, status, payment_status, total, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  })
});

// src/lib/mcp/tools/get_order.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
var get_order_default = defineTool5({
  name: "get_order",
  title: "Get order details",
  description: "Fetch full details for one of the signed-in user's Houskase orders \u2014 items, shipping address, totals, status. RLS restricts to the caller's own orders.",
  inputSchema: {
    order_id: z4.string().trim().optional().describe("Order UUID."),
    order_number: z4.string().trim().optional().describe("Order number (alternative to order_id).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("get_order", async ({ order_id, order_number }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    if (!order_id && !order_number) return { content: [{ type: "text", text: "Provide either order_id or order_number." }], isError: true };
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("orders").select("*, order_items(*)").limit(1);
    q = order_id ? q.eq("id", order_id) : q.eq("order_number", order_number);
    const { data, error } = await q.maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Order not found (or not yours)." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { order: data }
    };
  })
});

// src/lib/mcp/tools/get_order_timeline.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
var get_order_timeline_default = defineTool6({
  name: "get_order_timeline",
  title: "Get order status timeline",
  description: "Return the full status change history for one of the signed-in user's orders \u2014 every status transition with a timestamp, plus payment status changes.",
  inputSchema: {
    order_id: z5.string().trim().optional().describe("Order UUID."),
    order_number: z5.string().trim().optional().describe("Order number (alternative to order_id).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("get_order_timeline", async ({ order_id, order_number }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    if (!order_id && !order_number) return { content: [{ type: "text", text: "Provide either order_id or order_number." }], isError: true };
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("orders").select("id, order_number, status, payment_status, created_at, updated_at").limit(1);
    q = order_id ? q.eq("id", order_id) : q.eq("order_number", order_number);
    const { data: order, error: orderErr } = await q.maybeSingle();
    if (orderErr) return { content: [{ type: "text", text: `Error: ${orderErr.message}` }], isError: true };
    if (!order) return { content: [{ type: "text", text: "Order not found (or not yours)." }], isError: true };
    const { data: audits, error: auditErr } = await supabase.from("audit_log").select("action, old_data, new_data, created_at").eq("table_name", "orders").eq("row_id", order.id).order("created_at", { ascending: true });
    const timeline = [
      { at: order.created_at, event: "order_created", to: order.status }
    ];
    if (!auditErr && audits) {
      for (const row of audits) {
        if (row.action !== "orders.update") continue;
        const oldStatus = row.old_data?.status;
        const newStatus = row.new_data?.status;
        if (oldStatus !== newStatus) {
          timeline.push({ at: row.created_at, event: "status_changed", from: oldStatus, to: newStatus });
        }
        const oldPay = row.old_data?.payment_status;
        const newPay = row.new_data?.payment_status;
        if (oldPay !== newPay) {
          timeline.push({ at: row.created_at, event: "payment_status_changed", from: oldPay, to: newPay });
        }
      }
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ order, timeline }, null, 2) }],
      structuredContent: { order, timeline }
    };
  })
});

// src/lib/mcp/tools/list_my_rfqs.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z6 } from "npm:zod@^3.25.76";
var list_my_rfqs_default = defineTool7({
  name: "list_my_rfqs",
  title: "List my quote requests",
  description: "List the signed-in user's bulk quote requests (RFQs). RLS restricts to the caller's own RFQs.",
  inputSchema: {
    limit: z6.number().int().min(1).max(50).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("list_my_rfqs", async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("rfq_requests").select("id, rfq_number, status, product_name, quantity, message, quoted_price, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rfqs: data ?? [] }
    };
  })
});

// src/lib/mcp/tools/create_rfq.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z7 } from "npm:zod@^3.25.76";
var create_rfq_default = defineTool8({
  name: "create_rfq",
  title: "Create bulk quote request (RFQ)",
  description: "Create a Houskase bulk quote request (RFQ) for the signed-in user with a list of products, quantities, and optional notes. Returns the RFQ number.",
  inputSchema: {
    items: z7.array(
      z7.object({
        product_id: z7.string().trim().min(1).describe("Product UUID."),
        quantity: z7.number().int().min(1).describe("Requested quantity."),
        target_price: z7.number().optional().describe("Optional target price per unit (INR)."),
        variation_id: z7.string().trim().optional().describe("Optional product variation UUID.")
      })
    ).min(1).describe("Line items for the quote request."),
    notes: z7.string().trim().optional().describe("Optional message to the sales team."),
    company_name: z7.string().trim().optional().describe("Optional company name (for B2B)."),
    gst_number: z7.string().trim().optional().describe("Optional GST number (for B2B).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: withAudit("create_rfq", async ({ items, notes, company_name, gst_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: profile } = await supabase.from("profiles").select("full_name, email, phone, buyer_type").eq("user_id", userId).maybeSingle();
    const productIds = Array.from(new Set(items.map((i) => i.product_id)));
    const { data: products, error: prodErr } = await supabase.from("products").select("id, name").in("id", productIds);
    if (prodErr) return { content: [{ type: "text", text: `Error: ${prodErr.message}` }], isError: true };
    const nameById = new Map((products ?? []).map((p) => [p.id, p.name]));
    const missing = items.filter((i) => !nameById.has(i.product_id));
    if (missing.length > 0) {
      return {
        content: [{ type: "text", text: `Unknown product ids: ${missing.map((m) => m.product_id).join(", ")}` }],
        isError: true
      };
    }
    const totalQty = items.reduce((sum, i) => sum + i.quantity, 0);
    const headlineName = items.length === 1 ? nameById.get(items[0].product_id) : `${items.length} products (bulk)`;
    const { data: rfq, error: rfqErr } = await supabase.from("rfq_requests").insert({
      user_id: userId,
      buyer_type: profile?.buyer_type ?? "shop",
      full_name: profile?.full_name ?? ctx.getUserEmail?.() ?? "",
      email: profile?.email ?? ctx.getUserEmail?.() ?? "",
      phone: profile?.phone ?? "",
      company_name: company_name ?? null,
      gst_number: gst_number ?? null,
      product_name: headlineName,
      product_id: items.length === 1 ? items[0].product_id : null,
      quantity: totalQty,
      target_price: items.length === 1 ? items[0].target_price ?? null : null,
      message: notes ?? null,
      status: "pending"
    }).select("id, rfq_number").single();
    if (rfqErr || !rfq) {
      return { content: [{ type: "text", text: `Failed to create RFQ: ${rfqErr?.message ?? "unknown"}` }], isError: true };
    }
    const lineRows = items.map((i) => ({
      rfq_id: rfq.id,
      product_id: i.product_id,
      variation_id: i.variation_id ?? null,
      product_name: nameById.get(i.product_id),
      quantity: i.quantity,
      target_price: i.target_price ?? null
    }));
    const { error: itemsErr } = await supabase.from("rfq_items").insert(lineRows);
    if (itemsErr) {
      return {
        content: [
          {
            type: "text",
            text: `RFQ created (${rfq.rfq_number}) but failed to save line items: ${itemsErr.message}`
          }
        ],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `RFQ ${rfq.rfq_number} submitted with ${items.length} product(s), total quantity ${totalQty}. The Houskase sales team will respond with a quote.`
        }
      ],
      structuredContent: {
        rfq_id: rfq.id,
        rfq_number: rfq.rfq_number,
        item_count: items.length,
        total_quantity: totalQty
      }
    };
  })
});

// src/lib/mcp/tools/initiate_checkout.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z8 } from "npm:zod@^3.25.76";
var APP_URL = "https://houskase.lovable.app";
var initiate_checkout_default = defineTool9({
  name: "initiate_checkout",
  title: "Start checkout for my cart",
  description: "Create a pending order from the signed-in user's cart and return a checkout URL to complete payment in the browser. Requires a shipping address.",
  inputSchema: {
    shipping_address: z8.object({
      full_name: z8.string().trim().min(1),
      phone: z8.string().trim().min(1),
      line1: z8.string().trim().min(1),
      line2: z8.string().trim().optional(),
      city: z8.string().trim().min(1),
      state: z8.string().trim().min(1),
      pincode: z8.string().trim().min(1),
      country: z8.string().trim().optional()
    }).describe("Shipping address for the order."),
    notes: z8.string().trim().optional().describe("Optional order notes."),
    use_same_billing_address: z8.boolean().optional().describe("Use shipping address for billing (default true).")
  },
  // Charging money is a destructive/irreversible action from the agent's POV.
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: withAudit("initiate_checkout", async ({ shipping_address, notes, use_same_billing_address }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: cart, error: cartErr } = await supabase.from("cart_items").select("product_id, variation_id, quantity").eq("user_id", ctx.getUserId());
    if (cartErr) return { content: [{ type: "text", text: `Error: ${cartErr.message}` }], isError: true };
    if (!cart || cart.length === 0) {
      return { content: [{ type: "text", text: "Your cart is empty. Add items first." }], isError: true };
    }
    const { data: orderResult, error: orderErr } = await supabase.functions.invoke("create-order", {
      body: {
        items: cart,
        shipping_address,
        billing_address: use_same_billing_address === false ? void 0 : shipping_address,
        notes
      }
    });
    if (orderErr || !orderResult?.order) {
      return {
        content: [{ type: "text", text: `Failed to create order: ${orderErr?.message ?? "unknown error"}` }],
        isError: true
      };
    }
    const order = orderResult.order;
    let razorpayOrderId = null;
    const { data: rzp, error: rzpErr } = await supabase.functions.invoke("create-razorpay-order", {
      body: { order_id: order.id }
    });
    if (!rzpErr && rzp?.razorpay_order_id) {
      razorpayOrderId = rzp.razorpay_order_id;
    }
    const checkoutUrl = `${APP_URL}/checkout?order_id=${order.id}`;
    const message = `Order ${order.order_number} created for \u20B9${order.total}. Open ${checkoutUrl} in your browser to complete payment via Razorpay (UPI / cards / netbanking / wallets).`;
    return {
      content: [{ type: "text", text: message }],
      structuredContent: {
        order_id: order.id,
        order_number: order.order_number,
        total: order.total,
        razorpay_order_id: razorpayOrderId,
        checkout_url: checkoutUrl,
        note: "Payment must be completed in a browser \u2014 Razorpay uses a JS modal, not a hosted URL."
      }
    };
  })
});

// src/lib/mcp/tools/get_my_profile.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_my_profile_default = defineTool10({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's Houskase profile (name, phone, buyer type).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("get_my_profile", async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("id, full_name, phone, email, buyer_type").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  })
});

// src/lib/mcp/index.ts
var projectRef = "cxyfwxbirzskvoesgtia";
var mcp_default = defineMcp({
  name: "houskase-mcp",
  title: "Houskase",
  version: "0.2.0",
  instructions: "Tools for Houskase \u2014 India's premium household essentials store. Browse the catalog with search_products / get_product / list_categories. Read the signed-in user's own data with list_my_orders / get_order / get_order_timeline / list_my_rfqs / get_my_profile (all RLS-protected). Mutating tools: initiate_checkout (creates a pending order and returns a browser URL to finish paying) and create_rfq (submits a bulk quote request).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_products_default,
    get_product_default,
    list_categories_default,
    list_my_orders_default,
    get_order_default,
    get_order_timeline_default,
    list_my_rfqs_default,
    create_rfq_default,
    initiate_checkout_default,
    get_my_profile_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
